name: build and upload whl

on:
  push:
    branch:
      - 'release*'

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python.3.6.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.x
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install yapf wheel twine
          npm install
      - name: Build and upload wheel
        run: |
          python setup.py bdist_wheel
          for i in $(ls dist | grep .whl)
          do
            echo $i
            twine check dist/$i
            twine upload -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} dist/$i
          done
